version: '3'

services:
  site_db:
    container_name: site_db
    image: mysql:5.7.32
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=site_wpbp
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - default

  site_wordpress:
    container_name: site_wordpress
    image: wordpress:5.9.2-fpm-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=site_db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=site_wpbp
    volumes:
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - site_db
    networks:
      - default

  site_web:
    container_name: site_web
    image: "nginx:1.13.8-alpine"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=site.meudominio.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=site.meudominio.com
      - LETSENCRYPT_EMAIL=admin@meudominio.com
    depends_on:
      - site_wordpress
    networks:
      - default

volumes:
  wordpress:
  dbdata:

networks:
  default:
    external:
      name: nginx-proxy